services:
  database:
    build:
      context: ../database/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s
volumes:
  db_data:
