services:
  database:
    build:
      context: ../database/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s

  api:
    build:
      context: ../api/
      additional_contexts:
        project_root: ../
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    healthcheck:
      test: curl http://localhost:8000/ping || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s

  web:
    build:
      context: ../web/
      args:
        - FRONTEND_API_URL="${FRONTEND_API_URL}"
    ports:
      - "80:80"
    environment:
      - API_PROXY_URL="${API_PROXY_URL}"
    healthcheck:
      test: curl http://localhost:80 || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s
volumes:
  db_data:
