name: Build API Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --build-context project_root=../ --file Dockerfile --tag anomaly-detection-api:$(date +%s)
