name: Build Angular/Nginx Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg FRONTEND_API_URL=${{ vars.FRONTEND_API_URL }} --tag anomaly-detection-frontend:$(date +%s)
